version: '3.8'

services:
  declare:
    build: .
    container_name: declare
    ports:
      - "5173:5173"
    volumes:
      - ./dashboards/src:/usr/src/app/src
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"

  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal
    environment:
      - TEMPORAL_DB=clickhouse
      - TEMPORAL_DB_PORT=9000
    ports:
      - "7233:7233"

  temporal-web:
    image: temporalio/web:latest
    container_name: temporal-web
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
    ports:
      - "8088:8088"