# fly.toml app configuration file generated for declare-on-fly on 2024-10-08T06:53:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'declare-on-fly'
primary_region = 'ewr'

[build]
  dockerfile = './Dockerfile'

[deploy]
  strategy = 'immediate'

[processes]
  app = '/app/entrypoint.sh'

[[services]]
  protocol = 'tcp'
  internal_port = 5731
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.http_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "data"
  destination = "/data"
  initial_size = "20gb" # optional - the size of the volume created on first deploy

