# This docker image listens for changes in models/* and overwrites the database
# schema.
FROM node:latest
WORKDIR /usr/src/app
COPY ../.declare/hot-reload-models/package* .
RUN npm install
COPY ../.declare/hot-reload-models .

ENV NODE_ENV=production
ENV CHOKIDAR_USEPOLLING=true

CMD ["npx", "nodemon", "index.js", "--watch", "models", "-e", "*"]
