# This docker image listens for changes in models/* and overwrites the database
# schema.
FROM node:latest
WORKDIR /usr/src/app
COPY ../.declare/hot-model-reloader .
RUN npm install

ENV NODE_ENV=production

CMD ["npx", "nodemon", "index.js", "--watch", "models/**/definition.sql", "-e", "*"]
