FROM oven/bun:1 AS base
WORKDIR /usr/src/app
COPY .declare/dashboards .
COPY dashboards/package* .
RUN bun install

EXPOSE 5173

ENV NODE_ENV=development

CMD ["bun", "run", "dev", "--","--host", "0.0.0.0"]
