FROM node:latest
WORKDIR /usr/src/app
COPY .declare/dashboards .
COPY dashboards/package* .
RUN mkdir user_dashboards
COPY dashboards user_dashboards
RUN npm install

EXPOSE 5173

ENV NODE_ENV=development

CMD ["npm", "run", "dev", "--","--host", "0.0.0.0"]
