# Serve /api/**/** to `select * from **.**` against clickhouse
FROM oven/bun:1 AS base
WORKDIR /usr/src/app
COPY ../.declare/serve-models-api .
RUN bun install

ENV NODE_ENV=production
EXPOSE 8001

CMD ["bun", "--watch", "index.js"]
