# This docker image listens for changes in models/* and overwrites the database
# schema.
FROM oven/bun:1 AS base
WORKDIR /usr/src/app
COPY ../__declare__/hot-model-reloader .
RUN bun install

ENV NODE_ENV=production

CMD ["bun", "--watch", "index.js"]
