# Serve /api/**/** to `select * from **.**` against clickhouse
FROM oven/bun:1 AS base
WORKDIR /usr/src/app
COPY ../__declare__/serve-models-api .
RUN bun install

ENV NODE_ENV=production
EXPOSE 9002

CMD ["bun", "--watch", "index.js"]
