FROM python:3.12-slim-bookworm
WORKDIR /usr/src/app
COPY ../ .
RUN pip install uv
RUN uv sync --frozen
EXPOSE 9999

CMD ["uv", "run", "watchmedo", "auto-restart", "--patterns=workflows/**/*.py", "--signal=SIGKILL", "--recursive", "--", "uv", "run", "python", "-m", "__declare__.workflows.main"]