FROM oven/bun:latest
WORKDIR /usr/src/app
COPY __declare__/studio .
RUN npm install
EXPOSE 3000

ENV NODE_ENV=development
ENV DUMMY_JWT

CMD ["bun", "run", "dev", "--","--host", "0.0.0.0", "--port", "3000"]
