FROM python:3.12-slim-bookworm
WORKDIR /usr/src/app
COPY ../__declare__ ./__declare__
COPY ../pyproject.toml .
COPY ../uv.lock .
COPY ../.env .
RUN pip install uv
RUN uv sync --frozen
EXPOSE 9999

CMD ["uv", "run", "watchmedo", "auto-restart", "--patterns=workflows/**", "--signal=SIGKILL", "--recursive", "--kill-after", "0", "-d", "workflows", "--", "uv", "run", "python", "-m", "__declare__.workflows.main"]